# Theme
remote_theme: daviddarnes/alembic

# Website pages
navigation_header:
   Home: /
   CFP: /cfp
   Committees: /committees
   Dates: /dates
   Paper submission: /submission
   Program: /program

# Site settings
encoding: utf-8 # Make sure the encoding is right
title: "RaSTEES '19"
logo: "/assets/img/logo.png"

# Site credits
navigation_footer:
   ""

# contact
contact:
   email: pl@sslab.ics.keio.ac.jp
